# Generated by Django 4.2.26 on 2025-11-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50)),
                ('torre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'DEPARTAMENTOS',
            },
        ),
        migrations.CreateModel(
            name='EstadoSistema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_barrera', models.CharField(default='Cerrada', max_length=50)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ESTADO_SISTEMA',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('codigo_recuperacion', models.CharField(blank=True, max_length=5, null=True)),
                ('codigo_expira', models.DateTimeField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('Operador', 'Operador')], default='Operador', max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', max_length=50)),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departamento')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_sensor', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Llavero', 'Llavero')], max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=50)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departamento')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'SENSORES',
            },
        ),
        migrations.CreateModel(
            name='EventoAcceso',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('ACCESO_VALIDO', 'Acceso Válido'), ('ACCESO_RECHAZADO', 'Acceso Rechazado'), ('ACCESO_DESCONOCIDO', 'Acceso Desconocido'), ('APERTURA_MANUAL', 'Apertura Manual'), ('CIERRE_MANUAL', 'Cierre Manual'), ('APERTURA_MANUAL (APP)', 'Apertura Manual (APP)'), ('CIERRE_MANUAL (APP)', 'Cierre Manual (APP)')], max_length=100)),
                ('resultado', models.CharField(choices=[('PERMITIDO', 'Permitido'), ('DENEGADO', 'Denegado'), ('0', 'Sin resultado')], max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_departamento', models.ForeignKey(blank=True, db_column='id_departamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.departamento')),
                ('id_sensor', models.ForeignKey(blank=True, db_column='id_sensor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sensor')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
            options={
                'db_table': 'EVENTOS_ACCESO',
            },
        ),
    ]
